---
- name: Copy files for phpMyAdmin
  copy:
    src: ./roles/phpma/templates/{{ item.src }}
    dest: /tmp/phpma/{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: config.inc.php.j2, dest: config.inc.php }

- name: Build phpMyAdmin image from Dockerfile
  community.docker.docker_image:
    name: phpma
    tag: my_img
    source: build
    build:
      path: /tmp/phpma
  environment:
      PMA_HOST: mariadb

- name: Run phpMyAdmin Container
  community.docker.docker_container:
    name: phpma
    image: phpma:my_img
    restart_policy: always
    volumes:
      - phpma_data:/var/www/phpmyadmin
    networks:
      - name: inception_network
  